In [14]:
import pandas as pd
import os

#lista de Arquivos
caminho_pasta = r"C:\Users\Guarnieri\Desktop\Hashtag_Python\7_days_of_code\tabelas_fornecidas\dados_emprestimos"

arquivos_csv = [os.path.join(caminho_pasta, f) for f in os.listdir(caminho_pasta) if f.endswith('.csv')]

dataframes = [pd.read_csv(arquivo) for arquivo in arquivos_csv]
df_concatenado = pd.concat(dataframes, ignore_index=True)

print("Arquivos concatenados com sucesso.")

Arquivos concatenados com sucesso.

In [15]:
display(df_concatenado.head())

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO
4,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO

In [16]:
#Leitura do arquivo Parquet
acervo_parquet = pd.read_parquet(r'C:\Users\Guarnieri\Desktop\Hashtag_Python\7_days_of_code\tabelas_fornecidas\dados_exemplares.parquet')
display(acervo_parquet)

,id_exemplar,codigo_barras,colecao,biblioteca,status_material,localizacao,registro_sistema
index,,,,,,,
0,5,L000003,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,694,1
1,4,L000002,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,688,1
2,3,L000001,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,638,1
3,7,L000114,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,616,5
5,10,L000041,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,657,15
...,...,...,...,...,...,...,...
568580,1353472,2021011150,Acervo Circulante,Biblioteca Setorial do Núcleo de Educação da I...,REGULAR,951,268231
568581,1353473,2019013454,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,997,268233
568582,1353474,2019012811,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,987,268234
568583,1353475,2019013451,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,764,268235
568584,1353476,2019012276,Acervo Circulante,Biblioteca Central Zila Mamede,ESPECIAL,962,268236

In [17]:
#Junção dos arquivos
bases_consolidadas = df_concatenado.merge(acervo_parquet)

### Remoção de Duplicatas

In [18]:
bases_consolidadas = bases_consolidadas.drop_duplicates()

### Removendo datas do codigo de barras

In [19]:
bases_consolidadas['codigo_barras'] = bases_consolidadas['codigo_barras'].str.split("_").str[0]

### Salvar arquivo

In [20]:
caminho_salvar = r'C:\Users\Guarnieri\Desktop\Hashtag_Python\7_days_of_code\data'
bases_consolidadas.to_csv(f"{caminho_salvar}\\Base_consolidada.csv", index=False)

In [21]:
display(bases_consolidadas)

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,registro_sistema
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,4225
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,70865,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647,25009
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,195347,Acervo Circulante,Biblioteca Setorial Prof. Rodolfo Helinski - E...,REGULAR,640,75019
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,131639,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,609,44494
8,709688,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO,225646,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,686,91736
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2072553,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256297,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,684,110098
2072554,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256406,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,628,110171
2072555,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,807821,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,653,134173
2072556,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,804885,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,675,67712
2072557,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,1099777,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,14,205153