- Tipo de vínculo: tipo_vinculo_usuario	
- Coleção: colecao
- Biblioteca : biblioteca
- Classificação geral da CDU : CDU_geral

In [ ]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guarnieri\Desktop\Hashtag_Python\7_days_of_code\data\Base_consolidada.csv")
display(df.head())

“Como se distribuem os empréstimos de exemplares pelos tipos de vínculo dos usuários?”
Desta forma, a diretoria poderá entender qual é o público que está utilizando a biblioteca e assim tomar decisões em continuar com a estratégia de negócio atual ou modificá-la.

In [ ]:
exemplares_colecao = df.groupby(['tipo_vinculo_usuario'])['id_exemplar'].count().reset_index()
exemplares_colecao.columns = ['Coleção','Quantidade de Exemplares']
exemplares_colecao = exemplares_colecao.sort_values(by='Quantidade de Exemplares', ascending=False)
display(exemplares_colecao)

Quais coleções são mais emprestadas?
Da mesma forma, as coleções. Ranquear as coleções mais emprestadas pelo público, será bastante importante para a estratégia atual.

In [ ]:
exemplares_colecao = df.groupby(['colecao'])['id_exemplar'].count().reset_index()
exemplares_colecao.columns = ['Coleção','Quantidade de Exemplares']
exemplares_colecao = exemplares_colecao.sort_values(by='Quantidade de Exemplares', ascending=False)
display(exemplares_colecao)

Quais são as bibliotecas com mais ou menos quantidade de empréstimos?
Assim, a diretoria conseguirá entender onde ela deverá melhorar e focar suas iniciativas.

In [23]:
exemplares_colecao = df.groupby(['biblioteca'])['id_exemplar'].count().reset_index()
exemplares_colecao.columns = ['biblioteca','Quantidade de Exemplares']
exemplares_colecao = exemplares_colecao.sort_values(by='Quantidade de Exemplares', ascending=False)
display(exemplares_colecao)

,biblioteca,Quantidade de Exemplares
0,Biblioteca Central Zila Mamede,1426122
16,Biblioteca Setorial do Centro Ciências da Saúd...,118614
14,Biblioteca Setorial da Faculdade de Ciências d...,77609
5,Biblioteca Setorial Prof. Alberto Moreira Camp...,66447
13,Biblioteca Setorial Profª. Maria Lúcia da Cost...,61478
1,Biblioteca Setorial Bertha Cruz Enders - ­Esco...,46040
17,Biblioteca Setorial do Centro de Ciências Huma...,40744
2,Biblioteca Setorial Dr. Paulo Bezerra - EMCM/R...,32097
12,Biblioteca Setorial Profª. Maria José Mamede G...,29089
10,Biblioteca Setorial Prof. Rodolfo Helinski - E...,27219
7,Biblioteca Setorial Prof. Francisco Gurgel De ...,26923
19,Biblioteca Setorial do Núcleo de Educação da I...,23656
11,Biblioteca Setorial Prof. Ronaldo Xavier de Ar...,22749
4,Biblioteca Setorial Pe. Jaime Diniz - Escola d...,21476
18,Biblioteca Setorial do Departamento de Artes -...,17099
9,Biblioteca Setorial Prof. Leopoldo Nelson - ­C...,12900
15,Biblioteca Setorial do Centro Ciências Sociais...,10533
6,Biblioteca Setorial Prof. Dr. Marcelo Bezerra ...,5057
8,Biblioteca Setorial Prof. Horácio Nicolas Soli...,4098
3,Biblioteca Setorial Moacyr de Góes - CE,1036
21,Biblioteca Setorial Árvore do Conhecimento - I...,919
20,Biblioteca Setorial do Núcleo de Ensino Superi...,617

De quais temas da CDU são os exemplares emprestados?

In [24]:
exemplares_colecao = df.groupby(['CDU_geral'])['id_exemplar'].count().reset_index()
exemplares_colecao.columns = ['CDU_geral','Quantidade de Exemplares']
exemplares_colecao = exemplares_colecao.sort_values(by='Quantidade de Exemplares', ascending=False)
display(exemplares_colecao)

                               CDU_geral  Quantidade de Exemplares
1                     Ciências aplicadas                   1425473
2                       Ciências sociais                    369536
7         Matemática e ciências naturais                     68744
4  Generalidades. Ciência e conhecimento                     62521
8                               Religião                     62295
3                 Filosofia e psicologia                     60563
5         Geografia. Biografia. História                      7989
0                            Belas artes                      7911
6         Linguagem. Língua. Linguística                      7490